### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by asimon91** [gisce/project-dashboard#41]
Current tasks to do (priority ordered):

- [x] Add the capability of starting tasks. If task is not started, app should not create any workdone.
- [x] Fix paginator bug (if you're in page "8" and you change to another view that haves a paginator, it will remain in page 8, so current page must be cleared on every view).
- [x] Show all tasks button from user view (actually, it does nothing).
- [x] Translate "state" fields
- [x] Translate "priority" field
- [x] Start dashboard view development.
- [ ] Start timer development.

Feel free to extend this TODO list!

**Comment by gdalmau** [comment]
@asimon91 You can have a project that is similar to Trello boards

Some examples:
- https://github.com/gisce/sii/projects/1
- https://github.com/gisce/erp/projects/13

Or you can have a big Issue with all the items pending to do: https://github.com/gisce/erp/issues/4736

**Comment by asimon91** [comment]
Moved [here](https://github.com/gisce/project-dashboard/projects/1)
Thank you @gdalmau !!!
